# Generated by Django 4.2.4 on 2024-04-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_datetime', models.DateTimeField()),
                ('thumbnails_urls', models.JSONField()),
            ],
            options={
                'ordering': ['-published_datetime'],
            },
        ),
    ]
